# Makefile automatically generated by ghdl
# Version: GHDL 0.29 (20100109) [Sokcho edition] - GCC back-end code generator
# Command used to generate this makefile:
# /usr/lib/ghdl/bin/ghdl --gen-makefile --ieee=mentor alu_tb

GHDL=`which ghdl`
GHDLFLAGS= --ieee=mentor

# Default target
all: alu_tb alu busses cpu IO microprocessor mmu

clean:
	rm *.o

# Elaboration target
alu_tb: alu.o alu_tb.o
	$(GHDL) -e $(GHDLFLAGS) $@

alu: alu.o
	$(GHDL) -e $(GHDLFLAGS) $@

busses: buses.o
	$(GHDL) -e $(GHDLFLAGS) $@

cpu: cpu.o
	$(GHDL) -e $(GHDLFLAGS) $@

IO: IO.o
	$(GHDL) -e $(GHDLFLAGS) $@

microprocessor: microprocessor.o
	$(GHDL) -e $(GHDLFLAGS) $@

mmu: mmu.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: alu_tb
	$(GHDL) -r alu_tb $(GHDLRUNFLAGS)

# Targets to analyze files
alu_tb.o: alu_tb.vhd alu.o
	$(GHDL) -a $(GHDLFLAGS) $<

alu.o: alu.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

busses.o: buses.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

cpu.o: cpu.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

IO.o: IO.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

microprocessor.o: microprocessor.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

mmu.o: mmu.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

